// Generated by CoffeeScript 1.8.0
(function() {
  var options;

  options = {
    url: "http://www.omdbapi.com/?i=&t=zoolander",
    dataType: "json"
  };

  $(function() {
    return $.ajax({
      url: "http://www.omdbapi.com/?i=&t=zoolander",
      dataType: "json"
    }).done(function(data) {
      console.log(data.Title);
      console.log(data);
      $('.movieName').html(data.Title);
      $('span.year').html(data.Year);
      $('span.runTime').html(data.Runtime);
      $('span.rated').html(data.Rated);
      $('span.summary').html(data.Plot);
      $('span.actors').html(data.Actors);
      $('span.genre').html(data.Genre);
      $('span.director').html(data.Director);
      $('span.writer').html(data.Writer);
      $('span.language').html(data.Language);
      $('span.country').html(data.Country);
      $('span.awards').html(data.Awards);
      $('span.imdbId').html(data.imdbID);
      $('span.imdbRating').html(data.imdbRating);
      return $(".poster").html("<img src=\"" + data.Poster + "\" />");
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map
