// Generated by CoffeeScript 1.8.0
(function() {
  var options;

  options = {
    url: "http://www.omdbapi.com/?i=&t=zoolander",
    dataType: "json"
  };

  $(function() {
    return $('form').submit(function(e) {
      var input, name;
      e.preventDefault();
      input = $("form input[type='movie']");
      name = input.val();
      input.val('');
      console.log(data.Title);
      console.log(data);
      $(".poster").html("<img src=\"" + data.Poster + "\" />");
      $("span.title").html(data.Title);
      $("span.year").html(data.Year);
      $("span.actors").html(data.Actors);
      $("span.genre").html(data.Genre);
      $("span.imdbRating").html(data.imdbRating);
      return $("span.plot").html(data.Plot);
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map
